stages:
  - build
  - test
  - static_analysis
  - deploy

build-services:
  stage: build
  image: docker:24.0
  services:
    - name: docker:24.0-dind
  variables:
    DOCKER_HOST: tcp://192.168.65.7:2375  # Direct the Docker CLI to connect to the dind service
    DOCKER_DRIVER: overlay2         # Use the overlay2 storage driver for Docker
    DOCKER_TLS_CERTDIR: ""          # Disable Docker's TLS configuration (optional)
  script:
    - docker info
    - docker-compose build

test:
  stage: test
  script:
    - echo "Running tests"
    - pip install requests
    - python -m unittest discover tests/

static_analysis:
  stage: static_analysis
  script:
    - echo "Running static analysis"
    - pip install pylint
    - pylint service1/app.py
    - pylint service2/app.js

deploy:
  stage: deploy
  script:
    - echo "Deploying to production"
    - ssh -i /home/alvin/.ssh/Indomie.pem ubuntu@86.50.168.146 "cd DevOps_exercises && git pull && docker-compose -f docker-compose.yaml up -d"
  only:
    - project
