stages:
  - build
  - test
  - static_analysis
  - deploy

build-services:
  stage: build
  image: docker:latest  # Use Docker image for the job
  services:
    - name: docker:dind
      command: ["--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]  # Mount the Docker socket
  variables:
    DOCKER_HOST: tcp://docker:2375  # Use the Docker-in-Docker service
    DOCKER_TLS_CERTDIR: ""          # Disable TLS to use the Docker socket
  script:
    - docker-compose build


test:
  stage: test
  script:
    - echo "Running tests"
    - pip install requests
    - python -m unittest discover tests/

static_analysis:
  stage: static_analysis
  script:
    - echo "Running static analysis"
    - pip install pylint
    - pylint service1/app.py
    - pylint service2/app.js

deploy:
  stage: deploy
  script:
    - echo "Deploying to production"
    - ssh -i /home/alvin/.ssh/Indomie.pem ubuntu@86.50.168.146 "cd DevOps_exercises && git pull && docker-compose -f docker-compose.yaml up -d"
  only:
    - project
